### ISSUE TITLE
Cannot find name 'defineNuxtMswWorkerOption' (nor 'defineNuxtMswServerOption')

### ISSUE THREAD

**Issue by Dylan0916** [shunnNet/nuxt-msw#2]
Thank you very much for creating such a convenient tool!

I followed the instructions in the README, but I got the error: "Cannot find name 'defineNuxtMswWorkerOption'".
How can I resolve this?

Reproduction: [https://codesandbox.io/p/devbox/intelligent-keldysh-34hyh6](https://codesandbox.io/p/devbox/intelligent-keldysh-34hyh6)

![截圖 2024-11-11 上午10 26 10](https://github.com/user-attachments/assets/f8febc8c-b142-4206-adc5-3615f87cbc6b)

**Comment by shunnNet** [comment]
Hello, thank you for reporting the issue.

It seems that the link you provided is either private or incorrect, so I am unable to view your reproduction. Could you please make some adjustments? 

Thank you.

<img width="1198" alt="截圖 2024-11-11 20 58 44" src="https://github.com/user-attachments/assets/b13e236e-bdba-4206-b419-dde13a10ef51" />

**Comment by Dylan0916** [comment]
@shunnNet 
sorry, I updated the [link](https://codesandbox.io/p/devbox/intelligent-keldysh-34hyh6). could you try again?

I tried the method you provided, but the error still persists.

**Comment by shunnNet** [comment]
@Dylan0916 

Hello, After trying your demo, I still couldn’t pinpoint the cause, but it worked fine after forking it. Maybe an issue between CodeSandbox and Nuxt auto import.

I tried creating a working demo, you can fork it: https://codesandbox.io/p/devbox/3jdr8d

Have you tried operating in a local VSCode environment? I think similar issues shouldn’t occur in local VSCode.

**Comment by Dylan0916** [comment]
@shunnNet 

That's amazing! the forked indeed didn’t have any issues, how strange.😵‍💫

actually, I first encountered the issue on my local VSCode. then, in order to create a reproduction, I opened a workspace in CodeSandbox.

**Comment by shunnNet** [comment]
@Dylan0916 
Hello, you can try sharing your local repository, and I'll clone it to check it out.
Additionally, I have a few questions:

1. Are the other features of `nuxt-msw` functioning correctly?
2. Does the type information for other Nuxt auto-imports display correctly? For example, `useFetch`?

**Comment by Dylan0916** [comment]
@shunnNet 
Ah!!! I figured out the reason. I placed `@crazydos/nuxt-msw` in `modules` conditionally, the original intention was to activate msw only on CI 😅. my apologies!

I’ll close this issue, and thank you very much for your time.

**Comment by shunnNet** [comment]
@Dylan0916 
You can use `msw.enable` to toggle the module functionality in CI; this option is specifically designed for such scenarios, though it seems the documentation does not clearly mention it.

Currently, setting `msw.enable` to `false` also results in the loss of type hints, which may be inconvenient. I will work on a revision to address this issue.

Thank you for your collaboration!

**Comment by shunnNet** [comment]
Fixed [v1.0.2](https://github.com/shunnNet/nuxt-msw/releases/tag/v1.0.2)
